version: '3.7'
services:
  parser:
    build: ./services/parser
    command: python start.py
#    privileged: true
    volumes:
      - ./services/parser/:/usr/src/app/
    env_file:
      - ./.env
      - ./.env.bot
  db:
    image: postgres:12-alpine
    ports:
    - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
volumes:
  dbdata: